name=JC3248W535
version=1.4.0
author=Weerawat Poosommai
maintainer=Weerawat Poosommai
sentence=Arduino IDE library for ESP32-S3 + JC3248W535 dashboard projects.
paragraph=Includes board pin definitions, RGB565 dashboard icons, bundled fonts, and ready-to-use examples for Arduino IDE on ESP32-S3 + JC3248W535 320x480 touch LCD.
category=Display
url=https://github.com/wpoosommai/JC3248W535
architectures=esp32
includes=JC3248W535.h
